export const users = [
  {
    id: Math.random(),
    firstName: "Tri",
    lastName: "Pham",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: Math.random(),
    firstName: "Dung",
    lastName: "Le",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: Math.random(),
    firstName: "Dung",
    lastName: "Le",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: Math.random(),
    firstName: "Dung",
    lastName: "Le",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: Math.random(),
    firstName: "Dung",
    lastName: "Le",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
];
